### ISSUE TITLE
Online-form for supporters' association

### ISSUE THREAD

**Issue by alkock** [Giom-fm/ff-eppendorf-website#4]
As you can see @ https://ff-eppendorf.de/foerderverein/ there is a online form for new members.
We should integrate the Form into the website. There is a html-snippet which I can provide.

This is missing @ https://giom-fm.github.io/ff-eppendorf-website/foerderverein/

**Comment by Giom-fm** [comment]
I know.
For now I just took over the pdfs.
I will have to figure out how to implement the form with hugo.

**Comment by alkock** [comment]
Alrighty, let me know when you need anything :)

**Comment by Giom-fm** [comment]
I just saw that, the "Aufnahmeformular" is just an IFrame. The Form ist hosted by easyVerein. I think the easiest way would be to create a button that links to [this](https://easyverein.com/public/Eppendorf/applicationform/5724) page.

**Comment by alkock** [comment]
correct, lets do this!

**Comment by Giom-fm** [comment]
Ah I see a potential flaw over there. The URL changes to the URL from easyVerein which is a little fishy.
Then we will embed the IFrame into a normal Hugo page.

**Comment by alkock** [comment]
I'll look in to the portal internals if I can figure something out

**Comment by alkock** [comment]
Alright. Seems like the link will change, if we change the form. If that is not the case, then [this](https://easyverein.com/public/Eppendorf/applicationform/5724) link will stay.

**Comment by Giom-fm** [comment]
Hinode is clearly not designed to handle iframes.
For now, as workaround I added the "Online Formular" as a link to the external resource of easyVerein
